! $Id: StatTablesMod.f90 1.5 2011/09/05 13:18:29EDT 622325 Development  $
module StatTablesMod

!****h* source/StatTablesMod
!  NAME
!  StatTablesMod: OcactFortLib StatTablesMod module.
!  REVISION
!  $Revision: 1.5 $
!  MODULE DESCRIPTION
!  The StatTablesMod module contains functions used to calculate the inverse
!  value of the t-distribution and the z-distribution.
!  MODULE ROUTINES
!  CumDistInvT
!  CumDistInvZ
!*****

  ! All of the data in this file was generated by Excel 2003 using the
  ! functions TINV() and NORMSINV(). Data was rounded to 6 decimal
  ! places. See the workbook StatTables.xls.

  implicit none
  save

  private
  public :: CumDistInvT
  public :: CumDistInvZ

  ! Allow CumDistInvT to be the generic name for the specific subroutines.
!****f* StatTablesMod/CumDistInvT
!  NAME
!  CumDistInvT: This function returns the inverse value from the t-distribution.
!  DESCRIPTION
!  This function returns the inverse value from the t-distribution. The
!  number of degrees of freedom for the t-distribution are specified
!  by 'df'. The number of tails is specified by 'numTails'. This should
!  be either 1 or 2. When 'numTails' is 1, then 'prob' is the probability
!  being greater than the returned value. When 'numTails' is 2, then
!  'prob' is the probability of either being greater than the returned
!  value or being less than the negative of the returned value. This
!  function works like a table lookup, so there are only a finite number
!  of possible values that can be used for 'prob'. They are: 0.100, 0.050,
!  0.025, 0.010, 0.005, and 0.001.
!  RETURNS
!  Real or Double Precision (same type as 'prob'): Inverse value from the
!  t-distribution.
!  SYNOPSIS
!  real function CumDistInvT(df, prob, numTails) result(rv)
!  double precision function CumDistInvT(df, prob, numTails) result(rv)
!  ARGUMENTS
!  * df: Number of degrees of freedom for the t-distribution as an integer.
!  * prob: Probability as a real or double precision. Possible values: 0.100,
!    0.050, 0.025, 0.010, 0.005, and 0.001.
!  * numTails: Number of tails as an integer.
!  ARGUMENT DECLARATIONS
!  See ARGUMENTS section.
!*****
  interface CumDistInvT
    module procedure CumDistInvTReal, CumDistInvTDoublePrec
  end interface CumDistInvT

  ! Allow CumDistInvZ to be the generic name for the specific subroutines.
!****f* StatTablesMod/CumDistInvZ
!  NAME
!  CumDistInvZ: This function returns the inverse value from the z-distribution.
!  DESCRIPTION
!  This function returns the inverse value from the z-distribution (i.e.
!  the standard normal distribution). The number of tails is specified by
!  'numTails'. This should be either 1 or 2. When 'numTails' is 1, then
!  'prob' is the probability being greater than the returned value. When
!  'numTails' is 2, then 'prob' is the probability of either being greater
!  than the returned value or being less than the negative of the returned
!  value. This function works like a table lookup, so there are only a
!  finite number of possible values that can be used for 'prob'. They
!  are: 0.100, 0.050, 0.025, 0.010, 0.005, and 0.001.
!  RETURNS
!  Real or Double Precision (same type as 'prob'): Inverse value from the
!  z-distribution.
!  SYNOPSIS
!  real function CumDistInvZ(prob, numTails) result(rv)
!  double precision function CumDistInvZ(prob, numTails) result(rv)
!  ARGUMENTS
!  * prob: Probability as a real or double precision. Possible values: 0.100,
!    0.050, 0.025, 0.010, 0.005, and 0.001.
!  * numTails: Number of tails as an integer.
!  ARGUMENT DECLARATIONS
!  See ARGUMENTS section.
!*****
  interface CumDistInvZ
    module procedure CumDistInvZReal, CumDistInvZDoublePrec
  end interface CumDistInvZ

  ! Number of degrees of freedom (i.e. consecutive ones, starting at 1).
  integer, parameter :: NUM_DF = 100
  ! The 6 points are: 0.10, 0.05, 0.025, 0.01, 0.005, and 0.001.
  integer, parameter :: NUM_CRITICAL_POINTS = 6
  ! Small amount of tolerance due to rounding issues.
  double precision, parameter :: EPSILON = 0.0001d0

  ! The one-tailed values for the t-distribution.
  double precision, parameter, dimension(NUM_CRITICAL_POINTS, NUM_DF) :: &
    t_stat_oneTail = reshape( &
      (/3.077684d0,   6.313752d0,  12.706205d0,  31.820516d0,  63.656741d0, 318.308839d0,    &
        1.885618d0,   2.919986d0,   4.302653d0,   6.964557d0,   9.924843d0,  22.327125d0,    &
        1.637744d0,   2.353363d0,   3.182446d0,   4.540703d0,   5.840909d0,  10.214532d0,    &
        1.533206d0,   2.131847d0,   2.776445d0,   3.746947d0,   4.604095d0,   7.173182d0,    &
        1.475884d0,   2.015048d0,   2.570582d0,   3.364930d0,   4.032143d0,   5.893430d0,    &
        1.439756d0,   1.943180d0,   2.446912d0,   3.142668d0,   3.707428d0,   5.207626d0,    &
        1.414924d0,   1.894579d0,   2.364624d0,   2.997952d0,   3.499483d0,   4.785290d0,    &
        1.396815d0,   1.859548d0,   2.306004d0,   2.896459d0,   3.355387d0,   4.500791d0,    &
        1.383029d0,   1.833113d0,   2.262157d0,   2.821438d0,   3.249836d0,   4.296806d0,    &
        1.372184d0,   1.812461d0,   2.228139d0,   2.763769d0,   3.169273d0,   4.143700d0,    &
        1.363430d0,   1.795885d0,   2.200985d0,   2.718079d0,   3.105807d0,   4.024701d0,    &
        1.356217d0,   1.782288d0,   2.178813d0,   2.680998d0,   3.054540d0,   3.929633d0,    &
        1.350171d0,   1.770933d0,   2.160369d0,   2.650309d0,   3.012276d0,   3.851982d0,    &
        1.345030d0,   1.761310d0,   2.144787d0,   2.624494d0,   2.976843d0,   3.787390d0,    &
        1.340606d0,   1.753050d0,   2.131450d0,   2.602480d0,   2.946713d0,   3.732834d0,    &
        1.336757d0,   1.745884d0,   2.119905d0,   2.583487d0,   2.920782d0,   3.686155d0,    &
        1.333379d0,   1.739607d0,   2.109816d0,   2.566934d0,   2.898231d0,   3.645767d0,    &
        1.330391d0,   1.734064d0,   2.100922d0,   2.552380d0,   2.878440d0,   3.610485d0,    &
        1.327728d0,   1.729133d0,   2.093024d0,   2.539483d0,   2.860935d0,   3.579400d0,    &
        1.325341d0,   1.724718d0,   2.085963d0,   2.527977d0,   2.845340d0,   3.551808d0,    &
        1.323188d0,   1.720743d0,   2.079614d0,   2.517648d0,   2.831360d0,   3.527154d0,    &
        1.321237d0,   1.717144d0,   2.073873d0,   2.508325d0,   2.818756d0,   3.504992d0,    &
        1.319460d0,   1.713872d0,   2.068658d0,   2.499867d0,   2.807336d0,   3.484964d0,    &
        1.317836d0,   1.710882d0,   2.063899d0,   2.492159d0,   2.796939d0,   3.466777d0,    &
        1.316345d0,   1.708141d0,   2.059539d0,   2.485107d0,   2.787436d0,   3.450189d0,    &
        1.314972d0,   1.705618d0,   2.055529d0,   2.478630d0,   2.778715d0,   3.434997d0,    &
        1.313703d0,   1.703288d0,   2.051830d0,   2.472660d0,   2.770683d0,   3.421034d0,    &
        1.312527d0,   1.701131d0,   2.048407d0,   2.467140d0,   2.763262d0,   3.408155d0,    &
        1.311434d0,   1.699127d0,   2.045230d0,   2.462021d0,   2.756386d0,   3.396240d0,    &
        1.310415d0,   1.697261d0,   2.042272d0,   2.457262d0,   2.749996d0,   3.385185d0,    &
        1.309464d0,   1.695519d0,   2.039513d0,   2.452824d0,   2.744042d0,   3.374899d0,    &
        1.308573d0,   1.693889d0,   2.036933d0,   2.448678d0,   2.738481d0,   3.365306d0,    &
        1.307737d0,   1.692360d0,   2.034515d0,   2.444794d0,   2.733277d0,   3.356337d0,    &
        1.306952d0,   1.690924d0,   2.032244d0,   2.441150d0,   2.728394d0,   3.347934d0,    &
        1.306212d0,   1.689572d0,   2.030108d0,   2.437723d0,   2.723806d0,   3.340045d0,    &
        1.305514d0,   1.688298d0,   2.028094d0,   2.434494d0,   2.719485d0,   3.332624d0,    &
        1.304854d0,   1.687094d0,   2.026192d0,   2.431447d0,   2.715409d0,   3.325631d0,    &
        1.304230d0,   1.685954d0,   2.024394d0,   2.428568d0,   2.711558d0,   3.319030d0,    &
        1.303639d0,   1.684875d0,   2.022691d0,   2.425841d0,   2.707913d0,   3.312788d0,    &
        1.303077d0,   1.683851d0,   2.021075d0,   2.423257d0,   2.704459d0,   3.306878d0,    &
        1.302543d0,   1.682878d0,   2.019541d0,   2.420803d0,   2.701181d0,   3.301273d0,    &
        1.302035d0,   1.681952d0,   2.018082d0,   2.418470d0,   2.698066d0,   3.295951d0,    &
        1.301552d0,   1.681071d0,   2.016692d0,   2.416250d0,   2.695102d0,   3.290890d0,    &
        1.301090d0,   1.680230d0,   2.015368d0,   2.414134d0,   2.692278d0,   3.286072d0,    &
        1.300649d0,   1.679427d0,   2.014103d0,   2.412116d0,   2.689585d0,   3.281480d0,    &
        1.300228d0,   1.678660d0,   2.012896d0,   2.410188d0,   2.687013d0,   3.277098d0,    &
        1.299825d0,   1.677927d0,   2.011740d0,   2.408345d0,   2.684556d0,   3.272912d0,    &
        1.299439d0,   1.677224d0,   2.010635d0,   2.406581d0,   2.682204d0,   3.268910d0,    &
        1.299069d0,   1.676551d0,   2.009575d0,   2.404892d0,   2.679952d0,   3.265079d0,    &
        1.298714d0,   1.675905d0,   2.008559d0,   2.403272d0,   2.677793d0,   3.261409d0,    &
        1.298373d0,   1.675285d0,   2.007584d0,   2.401718d0,   2.675722d0,   3.257890d0,    &
        1.298045d0,   1.674689d0,   2.006647d0,   2.400225d0,   2.673734d0,   3.254512d0,    &
        1.297730d0,   1.674116d0,   2.005746d0,   2.398790d0,   2.671823d0,   3.251268d0,    &
        1.297426d0,   1.673565d0,   2.004879d0,   2.397410d0,   2.669985d0,   3.248149d0,    &
        1.297134d0,   1.673034d0,   2.004045d0,   2.396081d0,   2.668216d0,   3.245149d0,    &
        1.296853d0,   1.672522d0,   2.003241d0,   2.394801d0,   2.666512d0,   3.242261d0,    &
        1.296581d0,   1.672029d0,   2.002465d0,   2.393567d0,   2.664870d0,   3.239478d0,    &
        1.296319d0,   1.671553d0,   2.001717d0,   2.392377d0,   2.663287d0,   3.236795d0,    &
        1.296066d0,   1.671093d0,   2.000995d0,   2.391229d0,   2.661759d0,   3.234207d0,    &
        1.295821d0,   1.670649d0,   2.000298d0,   2.390119d0,   2.660283d0,   3.231709d0,    &
        1.295585d0,   1.670219d0,   1.999624d0,   2.389047d0,   2.658857d0,   3.229296d0,    &
        1.295356d0,   1.669804d0,   1.998971d0,   2.388011d0,   2.657479d0,   3.226964d0,    &
        1.295134d0,   1.669402d0,   1.998341d0,   2.387008d0,   2.656145d0,   3.224709d0,    &
        1.294920d0,   1.669013d0,   1.997730d0,   2.386037d0,   2.654854d0,   3.222527d0,    &
        1.294712d0,   1.668636d0,   1.997138d0,   2.385097d0,   2.653604d0,   3.220414d0,    &
        1.294511d0,   1.668271d0,   1.996564d0,   2.384186d0,   2.652393d0,   3.218368d0,    &
        1.294315d0,   1.667916d0,   1.996008d0,   2.383302d0,   2.651220d0,   3.216386d0,    &
        1.294126d0,   1.667572d0,   1.995469d0,   2.382446d0,   2.650081d0,   3.214463d0,    &
        1.293942d0,   1.667239d0,   1.994945d0,   2.381614d0,   2.648977d0,   3.212599d0,    &
        1.293763d0,   1.666914d0,   1.994437d0,   2.380807d0,   2.647905d0,   3.210789d0,    &
        1.293589d0,   1.666600d0,   1.993943d0,   2.380024d0,   2.646863d0,   3.209032d0,    &
        1.293421d0,   1.666294d0,   1.993464d0,   2.379262d0,   2.645852d0,   3.207326d0,    &
        1.293256d0,   1.665996d0,   1.992997d0,   2.378522d0,   2.644869d0,   3.205668d0,    &
        1.293097d0,   1.665707d0,   1.992543d0,   2.377802d0,   2.643913d0,   3.204056d0,    &
        1.292941d0,   1.665425d0,   1.992102d0,   2.377102d0,   2.642983d0,   3.202489d0,    &
        1.292790d0,   1.665151d0,   1.991673d0,   2.376420d0,   2.642078d0,   3.200964d0,    &
        1.292643d0,   1.664885d0,   1.991254d0,   2.375757d0,   2.641198d0,   3.199480d0,    &
        1.292500d0,   1.664625d0,   1.990847d0,   2.375111d0,   2.640340d0,   3.198035d0,    &
        1.292360d0,   1.664371d0,   1.990450d0,   2.374482d0,   2.639505d0,   3.196628d0,    &
        1.292224d0,   1.664125d0,   1.990063d0,   2.373868d0,   2.638691d0,   3.195258d0,    &
        1.292091d0,   1.663884d0,   1.989686d0,   2.373270d0,   2.637897d0,   3.193922d0,    &
        1.291961d0,   1.663649d0,   1.989319d0,   2.372687d0,   2.637123d0,   3.192619d0,    &
        1.291835d0,   1.663420d0,   1.988960d0,   2.372119d0,   2.636369d0,   3.191349d0,    &
        1.291711d0,   1.663197d0,   1.988610d0,   2.371564d0,   2.635632d0,   3.190111d0,    &
        1.291591d0,   1.662979d0,   1.988268d0,   2.371022d0,   2.634914d0,   3.188902d0,    &
        1.291473d0,   1.662765d0,   1.987934d0,   2.370493d0,   2.634212d0,   3.187722d0,    &
        1.291358d0,   1.662557d0,   1.987608d0,   2.369977d0,   2.633527d0,   3.186569d0,    &
        1.291246d0,   1.662354d0,   1.987290d0,   2.369472d0,   2.632858d0,   3.185444d0,    &
        1.291136d0,   1.662155d0,   1.986979d0,   2.368979d0,   2.632204d0,   3.184345d0,    &
        1.291029d0,   1.661961d0,   1.986674d0,   2.368497d0,   2.631565d0,   3.183271d0,    &
        1.290924d0,   1.661771d0,   1.986377d0,   2.368026d0,   2.630940d0,   3.182221d0,    &
        1.290821d0,   1.661585d0,   1.986086d0,   2.367566d0,   2.630330d0,   3.181194d0,    &
        1.290721d0,   1.661404d0,   1.985802d0,   2.367115d0,   2.629732d0,   3.180191d0,    &
        1.290623d0,   1.661226d0,   1.985523d0,   2.366674d0,   2.629148d0,   3.179209d0,    &
        1.290527d0,   1.661052d0,   1.985251d0,   2.366243d0,   2.628576d0,   3.178248d0,    &
        1.290432d0,   1.660881d0,   1.984984d0,   2.365821d0,   2.628016d0,   3.177308d0,    &
        1.290340d0,   1.660715d0,   1.984723d0,   2.365407d0,   2.627468d0,   3.176387d0,    &
        1.290250d0,   1.660551d0,   1.984467d0,   2.365002d0,   2.626931d0,   3.175486d0,    &
        1.290161d0,   1.660391d0,   1.984217d0,   2.364606d0,   2.626405d0,   3.174604d0,    &
        1.290075d0,   1.660234d0,   1.983971d0,   2.364217d0,   2.625891d0,   3.173739d0 /), &
      (/NUM_CRITICAL_POINTS, NUM_DF/))

  ! The two-tailed values for the t-distribution.
  double precision, parameter, dimension(NUM_CRITICAL_POINTS, NUM_DF) :: &
    t_stat_twoTail = reshape( &
      (/6.313752d0,  12.706205d0,  25.451700d0,  63.656741d0, 127.321336d0, 636.619249d0,    &
        2.919986d0,   4.302653d0,   6.205347d0,   9.924843d0,  14.089047d0,  31.599055d0,    &
        2.353363d0,   3.182446d0,   4.176535d0,   5.840909d0,   7.453319d0,  12.923979d0,    &
        2.131847d0,   2.776445d0,   3.495406d0,   4.604095d0,   5.597568d0,   8.610302d0,    &
        2.015048d0,   2.570582d0,   3.163381d0,   4.032143d0,   4.773341d0,   6.868827d0,    &
        1.943180d0,   2.446912d0,   2.968687d0,   3.707428d0,   4.316827d0,   5.958816d0,    &
        1.894579d0,   2.364624d0,   2.841244d0,   3.499483d0,   4.029337d0,   5.407883d0,    &
        1.859548d0,   2.306004d0,   2.751524d0,   3.355387d0,   3.832519d0,   5.041305d0,    &
        1.833113d0,   2.262157d0,   2.685011d0,   3.249836d0,   3.689662d0,   4.780913d0,    &
        1.812461d0,   2.228139d0,   2.633767d0,   3.169273d0,   3.581406d0,   4.586894d0,    &
        1.795885d0,   2.200985d0,   2.593093d0,   3.105807d0,   3.496614d0,   4.436979d0,    &
        1.782288d0,   2.178813d0,   2.560033d0,   3.054540d0,   3.428444d0,   4.317791d0,    &
        1.770933d0,   2.160369d0,   2.532638d0,   3.012276d0,   3.372468d0,   4.220832d0,    &
        1.761310d0,   2.144787d0,   2.509569d0,   2.976843d0,   3.325696d0,   4.140454d0,    &
        1.753050d0,   2.131450d0,   2.489880d0,   2.946713d0,   3.286039d0,   4.072765d0,    &
        1.745884d0,   2.119905d0,   2.472878d0,   2.920782d0,   3.251993d0,   4.014996d0,    &
        1.739607d0,   2.109816d0,   2.458051d0,   2.898231d0,   3.222450d0,   3.965126d0,    &
        1.734064d0,   2.100922d0,   2.445006d0,   2.878440d0,   3.196574d0,   3.921646d0,    &
        1.729133d0,   2.093024d0,   2.433440d0,   2.860935d0,   3.173725d0,   3.883406d0,    &
        1.724718d0,   2.085963d0,   2.423117d0,   2.845340d0,   3.153401d0,   3.849516d0,    &
        1.720743d0,   2.079614d0,   2.413845d0,   2.831360d0,   3.135206d0,   3.819277d0,    &
        1.717144d0,   2.073873d0,   2.405473d0,   2.818756d0,   3.118824d0,   3.792131d0,    &
        1.713872d0,   2.068658d0,   2.397875d0,   2.807336d0,   3.103997d0,   3.767627d0,    &
        1.710882d0,   2.063899d0,   2.390949d0,   2.796939d0,   3.090514d0,   3.745399d0,    &
        1.708141d0,   2.059539d0,   2.384610d0,   2.787436d0,   3.078199d0,   3.725144d0,    &
        1.705618d0,   2.055529d0,   2.378786d0,   2.778715d0,   3.066909d0,   3.706612d0,    &
        1.703288d0,   2.051830d0,   2.373417d0,   2.770683d0,   3.056520d0,   3.689592d0,    &
        1.701131d0,   2.048407d0,   2.368452d0,   2.763262d0,   3.046929d0,   3.673906d0,    &
        1.699127d0,   2.045230d0,   2.363846d0,   2.756386d0,   3.038047d0,   3.659405d0,    &
        1.697261d0,   2.042272d0,   2.359562d0,   2.749996d0,   3.029798d0,   3.645959d0,    &
        1.695519d0,   2.039513d0,   2.355568d0,   2.744042d0,   3.022118d0,   3.633456d0,    &
        1.693889d0,   2.036933d0,   2.351835d0,   2.738481d0,   3.014949d0,   3.621802d0,    &
        1.692360d0,   2.034515d0,   2.348338d0,   2.733277d0,   3.008242d0,   3.610913d0,    &
        1.690924d0,   2.032244d0,   2.345056d0,   2.728394d0,   3.001954d0,   3.600716d0,    &
        1.689572d0,   2.030108d0,   2.341969d0,   2.723806d0,   2.996047d0,   3.591147d0,    &
        1.688298d0,   2.028094d0,   2.339061d0,   2.719485d0,   2.990487d0,   3.582150d0,    &
        1.687094d0,   2.026192d0,   2.336316d0,   2.715409d0,   2.985244d0,   3.573675d0,    &
        1.685954d0,   2.024394d0,   2.333721d0,   2.711558d0,   2.980293d0,   3.565678d0,    &
        1.684875d0,   2.022691d0,   2.331264d0,   2.707913d0,   2.975609d0,   3.558120d0,    &
        1.683851d0,   2.021075d0,   2.328935d0,   2.704459d0,   2.971171d0,   3.550966d0,    &
        1.682878d0,   2.019541d0,   2.326723d0,   2.701181d0,   2.966961d0,   3.544184d0,    &
        1.681952d0,   2.018082d0,   2.324620d0,   2.698066d0,   2.962962d0,   3.537745d0,    &
        1.681071d0,   2.016692d0,   2.322618d0,   2.695102d0,   2.959157d0,   3.531626d0,    &
        1.680230d0,   2.015368d0,   2.320711d0,   2.692278d0,   2.955534d0,   3.525801d0,    &
        1.679427d0,   2.014103d0,   2.318891d0,   2.689585d0,   2.952079d0,   3.520251d0,    &
        1.678660d0,   2.012896d0,   2.317152d0,   2.687013d0,   2.948781d0,   3.514957d0,    &
        1.677927d0,   2.011740d0,   2.315490d0,   2.684556d0,   2.945630d0,   3.509901d0,    &
        1.677224d0,   2.010635d0,   2.313899d0,   2.682204d0,   2.942616d0,   3.505068d0,    &
        1.676551d0,   2.009575d0,   2.312375d0,   2.679952d0,   2.939730d0,   3.500443d0,    &
        1.675905d0,   2.008559d0,   2.310914d0,   2.677793d0,   2.936964d0,   3.496013d0,    &
        1.675285d0,   2.007584d0,   2.309512d0,   2.675722d0,   2.934311d0,   3.491766d0,    &
        1.674689d0,   2.006647d0,   2.308165d0,   2.673734d0,   2.931765d0,   3.487691d0,    &
        1.674116d0,   2.005746d0,   2.306870d0,   2.671823d0,   2.929318d0,   3.483777d0,    &
        1.673565d0,   2.004879d0,   2.305625d0,   2.669985d0,   2.926965d0,   3.480016d0,    &
        1.673034d0,   2.004045d0,   2.304426d0,   2.668216d0,   2.924701d0,   3.476398d0,    &
        1.672522d0,   2.003241d0,   2.303271d0,   2.666512d0,   2.922521d0,   3.472916d0,    &
        1.672029d0,   2.002465d0,   2.302158d0,   2.664870d0,   2.920420d0,   3.469562d0,    &
        1.671553d0,   2.001717d0,   2.301084d0,   2.663287d0,   2.918394d0,   3.466329d0,    &
        1.671093d0,   2.000995d0,   2.300047d0,   2.661759d0,   2.916440d0,   3.463210d0,    &
        1.670649d0,   2.000298d0,   2.299046d0,   2.660283d0,   2.914553d0,   3.460200d0,    &
        1.670219d0,   1.999624d0,   2.298078d0,   2.658857d0,   2.912729d0,   3.457294d0,    &
        1.669804d0,   1.998971d0,   2.297142d0,   2.657479d0,   2.910967d0,   3.454485d0,    &
        1.669402d0,   1.998341d0,   2.296237d0,   2.656145d0,   2.909262d0,   3.451769d0,    &
        1.669013d0,   1.997730d0,   2.295360d0,   2.654854d0,   2.907613d0,   3.449142d0,    &
        1.668636d0,   1.997138d0,   2.294511d0,   2.653604d0,   2.906015d0,   3.446598d0,    &
        1.668271d0,   1.996564d0,   2.293689d0,   2.652393d0,   2.904468d0,   3.444135d0,    &
        1.667916d0,   1.996008d0,   2.292891d0,   2.651220d0,   2.902968d0,   3.441749d0,    &
        1.667572d0,   1.995469d0,   2.292118d0,   2.650081d0,   2.901514d0,   3.439435d0,    &
        1.667239d0,   1.994945d0,   2.291367d0,   2.648977d0,   2.900103d0,   3.437192d0,    &
        1.666914d0,   1.994437d0,   2.290639d0,   2.647905d0,   2.898734d0,   3.435015d0,    &
        1.666600d0,   1.993943d0,   2.289931d0,   2.646863d0,   2.897404d0,   3.432901d0,    &
        1.666294d0,   1.993464d0,   2.289243d0,   2.645852d0,   2.896113d0,   3.430848d0,    &
        1.665996d0,   1.992997d0,   2.288575d0,   2.644869d0,   2.894857d0,   3.428854d0,    &
        1.665707d0,   1.992543d0,   2.287925d0,   2.643913d0,   2.893637d0,   3.426916d0,    &
        1.665425d0,   1.992102d0,   2.287292d0,   2.642983d0,   2.892450d0,   3.425031d0,    &
        1.665151d0,   1.991673d0,   2.286677d0,   2.642078d0,   2.891295d0,   3.423197d0,    &
        1.664885d0,   1.991254d0,   2.286078d0,   2.641198d0,   2.890171d0,   3.421413d0,    &
        1.664625d0,   1.990847d0,   2.285494d0,   2.640340d0,   2.889077d0,   3.419676d0,    &
        1.664371d0,   1.990450d0,   2.284926d0,   2.639505d0,   2.888011d0,   3.417985d0,    &
        1.664125d0,   1.990063d0,   2.284372d0,   2.638691d0,   2.886972d0,   3.416337d0,    &
        1.663884d0,   1.989686d0,   2.283832d0,   2.637897d0,   2.885960d0,   3.414732d0,    &
        1.663649d0,   1.989319d0,   2.283305d0,   2.637123d0,   2.884973d0,   3.413167d0,    &
        1.663420d0,   1.988960d0,   2.282791d0,   2.636369d0,   2.884010d0,   3.411641d0,    &
        1.663197d0,   1.988610d0,   2.282290d0,   2.635632d0,   2.883071d0,   3.410152d0,    &
        1.662979d0,   1.988268d0,   2.281801d0,   2.634914d0,   2.882154d0,   3.408699d0,    &
        1.662765d0,   1.987934d0,   2.281323d0,   2.634212d0,   2.881260d0,   3.407282d0,    &
        1.662557d0,   1.987608d0,   2.280856d0,   2.633527d0,   2.880386d0,   3.405897d0,    &
        1.662354d0,   1.987290d0,   2.280400d0,   2.632858d0,   2.879533d0,   3.404546d0,    &
        1.662155d0,   1.986979d0,   2.279955d0,   2.632204d0,   2.878699d0,   3.403225d0,    &
        1.661961d0,   1.986674d0,   2.279520d0,   2.631565d0,   2.877884d0,   3.401935d0,    &
        1.661771d0,   1.986377d0,   2.279094d0,   2.630940d0,   2.877088d0,   3.400674d0,    &
        1.661585d0,   1.986086d0,   2.278678d0,   2.630330d0,   2.876309d0,   3.399442d0,    &
        1.661404d0,   1.985802d0,   2.278271d0,   2.629732d0,   2.875547d0,   3.398236d0,    &
        1.661226d0,   1.985523d0,   2.277873d0,   2.629148d0,   2.874802d0,   3.397057d0,    &
        1.661052d0,   1.985251d0,   2.277483d0,   2.628576d0,   2.874073d0,   3.395904d0,    &
        1.660881d0,   1.984984d0,   2.277101d0,   2.628016d0,   2.873360d0,   3.394775d0,    &
        1.660715d0,   1.984723d0,   2.276728d0,   2.627468d0,   2.872661d0,   3.393670d0,    &
        1.660551d0,   1.984467d0,   2.276362d0,   2.626931d0,   2.871977d0,   3.392588d0,    &
        1.660391d0,   1.984217d0,   2.276003d0,   2.626405d0,   2.871308d0,   3.391529d0,    &
        1.660234d0,   1.983971d0,   2.275652d0,   2.625891d0,   2.870652d0,   3.390491d0 /), &
      (/NUM_CRITICAL_POINTS, NUM_DF/))

  ! The one- and two-tailed values for the t-distribution, for 250 d.f..
  double precision, parameter, dimension(NUM_CRITICAL_POINTS, 2) :: &
    t_stat_df250 = (/1.284947d0, 1.650971d0, 1.969498d0, 2.341356d0, 2.595638d0, 3.123150d0, &
                     1.650971d0, 1.969498d0, 2.254983d0, 2.595638d0, 2.832166d0, 3.329867d0 /)

  ! The one- and two-tailed values for the t-distribution, for 500 d.f..
  double precision, parameter, dimension(NUM_CRITICAL_POINTS, 2) :: &
    t_stat_df500 = (/1.283247d0, 1.647907d0, 1.964720d0, 2.333829d0, 2.585698d0, 3.106612d0, &
                     1.647907d0, 1.964720d0, 2.248173d0, 2.585698d0, 2.819548d0, 3.310091d0 /)

  ! The one- and two-tailed values for the t-distribution, for 1000 d.f..
  double precision, parameter, dimension(NUM_CRITICAL_POINTS, 2) :: &
    t_stat_df1000 = (/1.282399d0, 1.646379d0, 1.962339d0, 2.330083d0, 2.580755d0, 3.098402d0, &
                      1.646379d0, 1.962339d0, 2.244783d0, 2.580755d0, 2.813278d0, 3.300283d0 /)

  ! The one- and two-tailed values for the t-distribution, for 5000 d.f..
  double precision, parameter, dimension(NUM_CRITICAL_POINTS, 2) :: &
    t_stat_df5000 = (/1.281721d0, 1.645158d0, 1.960438d0, 2.327094d0, 2.576813d0, 3.091863d0, &
                      1.645158d0, 1.960438d0, 2.242078d0, 2.576813d0, 2.808281d0, 3.292474d0 /)

  ! The one- and two-tailed values for the t-distribution, for 1000000000 d.f.
  ! (i.e. as the d.f. approaches infinity).
  double precision, parameter, dimension(NUM_CRITICAL_POINTS, 2) :: &
    t_stat_df1000000000 = (/1.281556d0, 1.644839d0, 1.959966d0, 2.326348d0, 2.575830d0, 3.090232d0, &
                            1.644839d0, 1.959966d0, 2.241402d0, 2.575830d0, 2.807032d0, 3.290528d0 /)

  ! The t-distribution, 1- and 2-tailed, in a single array. This third
  ! dimension is 1 for the 1-tailed test and 2 for the 2-tailed test.
  double precision, parameter, dimension(NUM_CRITICAL_POINTS, NUM_DF, 2) :: &
    t_stat = (/t_stat_oneTail, t_stat_twoTail/)

  ! The 1- and 2-tailed values for the z-distribution (standard normal).
  ! The second dimension is 1 for the 1-tailed test, and 2 for the 2-tailed test.
  double precision, parameter, dimension(NUM_CRITICAL_POINTS, 2) :: &
    z_stat = (/1.281552d0, 1.644854d0, 1.959964d0, 2.326348d0, 2.575829d0, 3.090232d0, &
               1.644854d0, 1.959964d0, 2.241403d0, 2.575829d0, 2.807034d0, 3.290527d0/)

  contains

!******************************************************************************
  real function CumDistInvTReal(df, prob, numTails) result(rv)

    integer, intent(in) :: df
    real, intent(in) :: prob
    integer, intent(in) :: numTails

    rv = real(CumDistInvT(df, dble(prob), numTails))

  end function CumDistInvTReal
!******************************************************************************
  double precision function CumDistInvTDoublePrec(df, prob, numTails) &
    result(rv)

    integer, intent(in) :: df
    double precision, intent(in) :: prob
    integer, intent(in) :: numTails
    integer :: ind

    if (numTails < 1 .or. numTails > 2) then
      write(6, '(A)') "Error in CumDistInvT. numTails must be either 1 or 2."
      stop
    end if

    ind = GetIndex(prob)
    select case (df)
    case (1:NUM_DF)
      rv = t_stat(ind, df, numTails)
    case (NUM_DF+1:250)
      rv = Interpolate(NUM_DF, t_stat(ind, NUM_DF, numTails), &
        250, t_stat_df250(ind, numTails), df)
    case (251:500)
      rv = Interpolate(250, t_stat_df250(ind, numTails), &
        500, t_stat_df500(ind, numTails), df)
    case (501:1000)
      rv = Interpolate(500, t_stat_df500(ind, numTails), &
        1000, t_stat_df1000(ind, numTails), df)
    case (1001:5000)
      rv = Interpolate(1000, t_stat_df1000(ind, numTails), &
        5000, t_stat_df5000(ind, numTails), df)
    case (5001:1000000000)
      rv = Interpolate(5000, t_stat_df5000(ind, numTails), &
        1000000000, t_stat_df1000000000(ind, numTails), df)
    case (1000000001:)
      rv = t_stat_df1000000000(ind, numTails)
    case default
      write(6, '(A)') &
        "Error in GetTStat(). Illegal number of degrees of freedom."
      stop
    end select

  end function CumDistInvTDoublePrec
!******************************************************************************
  real function CumDistInvZReal(prob, numTails) result(rv)

    real, intent(in) :: prob
    integer, intent(in) :: numTails

    rv = real(CumDistInvZDoublePrec(dble(prob), numTails))

  end function CumDistInvZReal
!******************************************************************************
  double precision function CumDistInvZDoublePrec(prob, numTails) result(rv)

    double precision, intent(in) :: prob
    integer, intent(in) :: numTails
    integer :: ind

    if (numTails < 1 .or. numTails > 2) then
      write(6, '(A)') "Error in CumDistInvZ. numTails must be either 1 or 2."
      stop
    end if

    ind = GetIndex(prob)
    rv = z_stat(ind, numTails)

  end function CumDistInvZDoublePrec
!******************************************************************************
  integer function GetIndex(prob) result(rv)

    double precision, intent(in) :: prob

    if (prob > 0.10 - EPSILON .and. prob < 0.10 + EPSILON) then
      rv = 1
    else if (prob > 0.05 - EPSILON .and. prob < 0.05 + EPSILON) then
      rv = 2
    else if (prob > 0.025 - EPSILON .and. prob < 0.025 + EPSILON) then
      rv = 3
    else if (prob > 0.01 - EPSILON .and. prob < 0.01 + EPSILON) then
      rv = 4
    else if (prob > 0.005 - EPSILON .and. prob < 0.005 + EPSILON) then
      rv = 5
    else if (prob > 0.001 - EPSILON .and. prob < 0.001 + EPSILON) then
      rv = 6
    else
      write(6, '(A, F10.4)') "Error in StatTablesMod, illegal probability: ", &
        prob
      stop
    end if

  end function GetIndex
!******************************************************************************
  double precision function Interpolate(x1, y1, x3, y3, x2) result(rv)

    integer, intent(in) :: x1, x3, x2
    double precision, intent(in) :: y1, y3

    rv = y1 + (dble(x2 - x1) / dble(x3 - x1)) * (y3 - y1)

  end function Interpolate
!******************************************************************************

end module StatTablesMod
